model_list:
  - model_name: granite-3.3-8b-instruct
    params:
      model: openai/ibm-granite/granite-3.3-8b-instruct
      api_base: os.environ/VLLM_INSTRUCT_URL
      api_key: "fake-key"

  - model_name: granite-embedding-278m
    params:
      model: openai/ibm-granite/granite-embedding-278m-multilingual
      api_base: os.environ/VLLM_EMBEDDING_URL
      api_key: "fake-key"

  - model_name: bge-reranker-v2-m3
    params:
      model: openai/BAAI/bge-reranker-v2-m3
      api_base: os.environ/VLLM_RERANKER_URL
      api_key: "fake-key"

  - model_name: granite-3-8b-instruct-wx
    params:
      model: watsonx/ibm/granite-3-8b-instruct
      api_key: os.environ/WATSONX_API_KEY
      watsonx_project_id: os.environ/WATSONX_PROJECT_ID
      api_base: os.environ/WATSONX_URL

  - model_name: granite-embedding-278m-multilingual-wx
    params:
      model: watsonx/ibm/granite-embedding-278m-multilingual
      api_key: os.environ/WATSONX_API_KEY
      watsonx_project_id: os.environ/WATSONX_PROJECT_ID
      api_base: os.environ/WATSONX_URL

  - model_name: ms-marco-minilm-l-12-v2-wx
    params:
      model: watsonx/cross-encoder/ms-marco-minilm-l-12-v2
      api_key: os.environ/WATSONX_API_KEY
      watsonx_project_id: os.environ/WATSONX_PROJECT_ID
      api_base: os.environ/WATSONX_URL

general_settings:
  master_key: os.environ/GATEWAY_MASTER_KEY

settings:
  request_timeout: 120
