apiVersion: v1
kind: Secret
metadata:
  name: "llm-gateway-credentials"
  labels:
    ai-services.io/application: {{ .Release.Name }}
    ai-services.io/template: {{ .Chart.Name }}
    ai-services.io/version: {{ default .Chart.AppVersion | quote }}
type: Opaque
stringData:
  master-key: "{{ .Values.llmGateway.masterKey }}"
  watsonx-api-key: "{{ .Values.llmGateway.watsonxApiKey }}"
  watsonx-project-id: "{{ .Values.llmGateway.watsonxProjectId }}"
