FROM localhost/prebuilder as prebuilder

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.7

RUN microdnf install -y python3.12-devel python3.12-pip \
        lcms2-devel openblas-devel freetype libicu libjpeg-turbo && \
    curl -o /tmp/epel-release.rpm https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    rpm -ivh /tmp/epel-release.rpm && \
    rm -f /tmp/epel-release.rpm && \
    microdnf install -y spatialindex-devel && \
    microdnf clean all && \
    rm -rf /usr/bin/python && rm -rf /usr/bin/python3 && \
    ln -s /usr/bin/pip3.12 /usr/bin/pip && ln -s /usr/bin/pip3.12 /usr/bin/pip3 && \
    ln -s /usr/bin/python3.12 /usr/bin/python && ln -s /usr/bin/python3.12 /usr/bin/python3

ENV DOCLING_MODELS_PATH=/var/docling-models

COPY requirements.txt .
COPY download_docling_models.py .

RUN --mount=type=bind,from=prebuilder,source=/wheels,target=/wheels,ro \
    python -m venv /var/venv && source /var/venv/bin/activate && \
    pip install --upgrade pip && \
    pip install  /wheels/*.whl -r requirements.txt \
        --extra-index-url https://wheels.developerfirst.ibm.com/ppc64le/linux \
        --prefer-binary && \
    pip cache purge && \
    python download_docling_models.py && \
    rm -rf ~/.cache/huggingface
