FROM localhost/prebuilder as prebuilder

FROM registry.access.redhat.com/ubi9/ubi:9.7

RUN yum install -y --setopt=tsflags=nodocs python3.12-devel python3.12-pip \
        lcms2-devel openblas-devel freetype libicu libjpeg-turbo && \
    yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm && \
    yum install -y spatialindex-devel && \
    yum clean all && rm -rf /var/cache/yum && \
    rm -rf /usr/bin/python && rm -rf /usr/bin/python3 && \
    ln -s /usr/bin/pip3.12 /usr/bin/pip && ln -s /usr/bin/pip3.12 /usr/bin/pip3 && \
    ln -s /usr/bin/python3.12 /usr/bin/python && ln -s /usr/bin/python3.12 /usr/bin/python3

ENV DOCLING_MODELS_PATH=/var/docling-models

COPY requirements.txt .
COPY download_docling_models.py .

RUN --mount=type=bind,from=prebuilder,source=/wheels,target=/wheels,ro \
    python -m venv /var/venv && source /var/venv/bin/activate && \
    pip install --upgrade pip && \
    pip install  /wheels/*.whl -r requirements.txt \
        --extra-index-url https://wheels.developerfirst.ibm.com/ppc64le/linux \
        --prefer-binary && \
    pip cache purge && \
    python download_docling_models.py
