FROM registry.access.redhat.com/ubi9/ubi:9.7

RUN yum install -y --setopt=tsflags=nodocs gcc-c++ python3.12-devel python3.12-pip && \
    yum clean all && rm -rf /var/cache/yum && \
    rm -rf /usr/bin/python && rm -rf /usr/bin/python3 && \
    ln -s /usr/bin/pip3.12 /usr/bin/pip && ln -s /usr/bin/pip3.12 /usr/bin/pip3 && \
    ln -s /usr/bin/python3.12 /usr/bin/python && ln -s /usr/bin/python3.12 /usr/bin/python3

COPY pre-requirements.txt .

# Build/Download wheels to the specific folder
RUN pip install --upgrade pip setuptools wheel && \
    pip wheel -r pre-requirements.txt \
    --wheel-dir=/wheels \
    --extra-index-url=https://wheels.developerfirst.ibm.com/ppc64le/linux/ \
    --prefer-binary
